<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CXMTCode.Plugins.MySQL80</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CXMTCode.Plugins.Common\CXMTCode.Plugins.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
  </ItemGroup>
</Project>
