<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CXMTCode.Plugins.MSSQL2019</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CXMTCode.Plugins.Common\CXMTCode.Plugins.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>
</Project>
