-- ============================================================================
-- CXMTCode 系统数据库 - Oracle 19C Enterprise 建库脚本
-- 执行用户：SYSDBA
-- 输出 Schema：CXMT_PLATFORM，前缀：CXMT_
-- ============================================================================

-- 表空间（路径请按实际部署修改）
CREATE TABLESPACE CXMT_DATA
  DATAFILE '/oradata/CXMT_DATA.dbf' SIZE 1G AUTOEXTEND ON NEXT 100M MAXSIZE 10G;

CREATE TABLESPACE CXMT_IDX
  DATAFILE '/oradata/CXMT_IDX.dbf'  SIZE 500M AUTOEXTEND ON NEXT 50M MAXSIZE 5G;

CREATE TABLESPACE CXMT_AUDIT
  DATAFILE '/oradata/CXMT_AUDIT.dbf' SIZE 2G AUTOEXTEND ON NEXT 200M MAXSIZE UNLIMITED;

-- 平台用户
CREATE USER CXMT_PLATFORM IDENTIFIED BY "CXMTCode#2026"
  DEFAULT TABLESPACE CXMT_DATA
  QUOTA UNLIMITED ON CXMT_DATA
  QUOTA UNLIMITED ON CXMT_IDX
  QUOTA UNLIMITED ON CXMT_AUDIT;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER,
      CREATE INDEX, CREATE VIEW, CREATE PROCEDURE TO CXMT_PLATFORM;

-- 序列
CREATE SEQUENCE SEQ_AUDIT_LOG_ID START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE SEQ_REQUEST_ID   START WITH 1 INCREMENT BY 1 CACHE 10;

-- ============================================================================
-- 业务表
-- ============================================================================

-- 用户表
CREATE TABLE CXMT_USERS (
    USER_ID         VARCHAR2(36)   NOT NULL,
    USER_NAME       VARCHAR2(64)   NOT NULL,
    PASSWORD_HASH   VARCHAR2(128)  NOT NULL,
    PASSWORD_SALT   VARCHAR2(64)   NOT NULL,
    DISPLAY_NAME    VARCHAR2(64)   NOT NULL,
    ROLE            NUMBER(1)      NOT NULL,
    DEPARTMENT_CODE VARCHAR2(32),
    DEPARTMENT_NAME VARCHAR2(64),
    EMAIL           VARCHAR2(128),
    IS_ACTIVE       NUMBER(1)      DEFAULT 1,
    LAST_LOGIN_AT   TIMESTAMP,
    LAST_LOGIN_IP   VARCHAR2(32),
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(36),
    UPDATED_AT      TIMESTAMP,
    UPDATED_BY      VARCHAR2(36),
    CONSTRAINT PK_CXMT_USERS PRIMARY KEY (USER_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;
CREATE UNIQUE INDEX IDX_CXMT_USERS_NAME ON CXMT_USERS(USER_NAME) TABLESPACE CXMT_IDX;
CREATE INDEX IDX_CXMT_USERS_ROLE ON CXMT_USERS(ROLE) TABLESPACE CXMT_IDX;
CREATE INDEX IDX_CXMT_USERS_DEPT ON CXMT_USERS(DEPARTMENT_CODE) TABLESPACE CXMT_IDX;

-- DB 连接配置
CREATE TABLE CXMT_DB_CONNECTIONS (
    CONNECTION_ID         VARCHAR2(36)   NOT NULL,
    CONNECTION_NAME       VARCHAR2(64)   NOT NULL,
    DATABASE_TYPE         NUMBER(1)      NOT NULL,
    ENVIRONMENT_TYPE      VARCHAR2(8)    NOT NULL,
    IS_ACTIVE_ENV         NUMBER(1)      DEFAULT 0,
    HOST                  VARCHAR2(128)  NOT NULL,
    PORT                  NUMBER(5)      NOT NULL,
    SERVICE_NAME          VARCHAR2(64),
    PDB_NAME              VARCHAR2(64),
    USERNAME              VARCHAR2(64)   NOT NULL,
    PASSWORD_ENC          VARCHAR2(256)  NOT NULL,
    CONNECTION_STRING_ENC VARCHAR2(512),
    STANDBY_HOST          VARCHAR2(128),
    STANDBY_PORT          NUMBER(5),
    STANDBY_SERVICE       VARCHAR2(64),
    IS_READ_ONLY          NUMBER(1)      DEFAULT 0,
    IS_STANDBY            NUMBER(1)      DEFAULT 0,
    IS_ACTIVE             NUMBER(1)      DEFAULT 1,
    TEST_RESULT           VARCHAR2(16),
    TESTED_AT             TIMESTAMP,
    DESCRIPTION           VARCHAR2(256),
    CREATED_AT            TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CREATED_BY            VARCHAR2(36),
    UPDATED_AT            TIMESTAMP,
    UPDATED_BY            VARCHAR2(36),
    CONSTRAINT PK_CXMT_DB_CONN PRIMARY KEY (CONNECTION_ID) USING INDEX TABLESPACE CXMT_IDX,
    CONSTRAINT CHK_ENV_TYPE   CHECK (ENVIRONMENT_TYPE IN ('TEST', 'PROD'))
) TABLESPACE CXMT_DATA;
CREATE UNIQUE INDEX IDX_CXMT_DB_CONN_NAME ON CXMT_DB_CONNECTIONS(CONNECTION_NAME) TABLESPACE CXMT_IDX;
CREATE INDEX IDX_CXMT_DB_CONN_TYPE   ON CXMT_DB_CONNECTIONS(DATABASE_TYPE) TABLESPACE CXMT_IDX;
CREATE INDEX IDX_CXMT_DB_CONN_ENV    ON CXMT_DB_CONNECTIONS(ENVIRONMENT_TYPE) TABLESPACE CXMT_IDX;
CREATE INDEX IDX_CXMT_DB_CONN_ACTIVE ON CXMT_DB_CONNECTIONS(IS_ACTIVE_ENV, ENVIRONMENT_TYPE) TABLESPACE CXMT_IDX;

-- 系统配置
CREATE TABLE CXMT_SYSTEM_CONFIG (
    CONFIG_KEY    VARCHAR2(64)   NOT NULL,
    CONFIG_VALUE  VARCHAR2(512)  NOT NULL,
    DESCRIPTION   VARCHAR2(256),
    CONFIG_GROUP  VARCHAR2(32)   DEFAULT 'SYSTEM',
    IS_EDITABLE   NUMBER(1)      DEFAULT 1,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT    TIMESTAMP,
    UPDATED_BY    VARCHAR2(36),
    CONSTRAINT PK_CXMT_SYS_CONFIG PRIMARY KEY (CONFIG_KEY) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;

INSERT INTO CXMT_SYSTEM_CONFIG VALUES ('CURRENT_ENVIRONMENT', 'PROD', '当前系统激活环境：PROD=生产 TEST=测试', 'SYSTEM', 1, SYSTIMESTAMP, NULL, NULL);
INSERT INTO CXMT_SYSTEM_CONFIG VALUES ('ALLOW_ENV_SWITCH',    '1',    '是否允许 SysAdmin 切换环境：1=允许',         'SYSTEM', 1, SYSTIMESTAMP, NULL, NULL);
COMMIT;

-- 审计日志（按季度分区）
CREATE TABLE CXMT_AUDIT_LOGS (
    LOG_ID           NUMBER(20)    NOT NULL,
    LOG_TIME         TIMESTAMP     NOT NULL,
    USER_ID          VARCHAR2(36)  NOT NULL,
    USER_NAME        VARCHAR2(64)  NOT NULL,
    USER_ROLE        NUMBER(1)     NOT NULL,
    ENVIRONMENT_TYPE VARCHAR2(8),
    OPERATION_TYPE   VARCHAR2(32)  NOT NULL,
    OPERATION_DESC   VARCHAR2(512) NOT NULL,
    TARGET_DATABASE  VARCHAR2(64),
    TARGET_TABLE     VARCHAR2(64),
    SQL_STATEMENT    CLOB,
    BEFORE_DATA      CLOB,
    AFTER_DATA       CLOB,
    CLIENT_IP        VARCHAR2(32),
    RESULT           VARCHAR2(16),
    HASH_VALUE       VARCHAR2(64)  NOT NULL,
    PREV_HASH        VARCHAR2(64),
    CONSTRAINT PK_CXMT_AUDIT_LOG PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_AUDIT
PARTITION BY RANGE (LOG_TIME) (
    PARTITION P2026Q1 VALUES LESS THAN (TO_DATE('2026-04-01', 'YYYY-MM-DD')),
    PARTITION P2026Q2 VALUES LESS THAN (TO_DATE('2026-07-01', 'YYYY-MM-DD')),
    PARTITION P2026Q3 VALUES LESS THAN (TO_DATE('2026-10-01', 'YYYY-MM-DD')),
    PARTITION P2026Q4 VALUES LESS THAN (TO_DATE('2027-01-01', 'YYYY-MM-DD')),
    PARTITION P2027Q1 VALUES LESS THAN (TO_DATE('2027-04-01', 'YYYY-MM-DD')),
    PARTITION P2027Q2 VALUES LESS THAN (TO_DATE('2027-07-01', 'YYYY-MM-DD')),
    PARTITION P2027Q3 VALUES LESS THAN (TO_DATE('2027-10-01', 'YYYY-MM-DD')),
    PARTITION P2027Q4 VALUES LESS THAN (TO_DATE('2028-01-01', 'YYYY-MM-DD')),
    PARTITION PMAX    VALUES LESS THAN (MAXVALUE)
);
CREATE INDEX IDX_AUDIT_USER    ON CXMT_AUDIT_LOGS(USER_ID)    LOCAL TABLESPACE CXMT_IDX;
CREATE INDEX IDX_AUDIT_TIME    ON CXMT_AUDIT_LOGS(LOG_TIME)   LOCAL TABLESPACE CXMT_IDX;
CREATE INDEX IDX_AUDIT_OP_TYPE ON CXMT_AUDIT_LOGS(OPERATION_TYPE) LOCAL TABLESPACE CXMT_IDX;
CREATE INDEX IDX_AUDIT_ENV     ON CXMT_AUDIT_LOGS(ENVIRONMENT_TYPE) TABLESPACE CXMT_IDX;

-- 变更申请
CREATE TABLE CXMT_CHANGE_REQUESTS (
    REQUEST_ID     VARCHAR2(32)  NOT NULL,
    STATUS         NUMBER(2)     NOT NULL,
    OPERATION_TYPE NUMBER(1)     NOT NULL,
    DATABASE_TYPE  NUMBER(1)     NOT NULL,
    CONNECTION_ID  VARCHAR2(36)  NOT NULL,
    TARGET_TABLE   VARCHAR2(128) NOT NULL,
    SQL_STATEMENT  CLOB          NOT NULL,
    SQL_HASH       VARCHAR2(64),
    REASON         VARCHAR2(512) NOT NULL,
    IMPACT_LEVEL   NUMBER(1)     NOT NULL,
    AFFECTED_ROWS  NUMBER(10),
    APPLICANT_ID   VARCHAR2(36)  NOT NULL,
    APPLICANT_ROLE NUMBER(1)     NOT NULL,
    APPROVER_ID    VARCHAR2(36),
    APPROVED_AT    TIMESTAMP,
    DRY_RUN_RESULT CLOB,
    BACKUP_TABLE   VARCHAR2(128),
    ROLLBACK_SQL   CLOB,
    EXECUTED_AT    TIMESTAMP,
    EXECUTED_BY    VARCHAR2(36),
    EXEC_RESULT    CLOB,
    ROLLED_BACK_AT TIMESTAMP,
    ROLLED_BACK_BY VARCHAR2(36),
    CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
    COMPLETED_AT   TIMESTAMP,
    CONSTRAINT PK_CXMT_CHG_REQ PRIMARY KEY (REQUEST_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;
CREATE INDEX IDX_CHG_REQ_STATUS    ON CXMT_CHANGE_REQUESTS(STATUS)       TABLESPACE CXMT_IDX;
CREATE INDEX IDX_CHG_REQ_APPLICANT ON CXMT_CHANGE_REQUESTS(APPLICANT_ID) TABLESPACE CXMT_IDX;

-- 表准入
CREATE TABLE CXMT_TABLE_ACCESS (
    ACCESS_ID       VARCHAR2(36)  NOT NULL,
    CONNECTION_ID   VARCHAR2(36)  NOT NULL,
    TABLE_NAME      VARCHAR2(128) NOT NULL,
    TABLE_SCHEMA    VARCHAR2(64),
    STATUS          NUMBER(1)     DEFAULT 0,
    DBA_APPROVER    VARCHAR2(36),
    BIZ_APPROVER    VARCHAR2(36),
    HAS_PRIMARY_KEY NUMBER(1),
    HAS_UNIQUE_IDX  NUMBER(1),
    RISK_LEVEL      NUMBER(1),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    APPROVED_AT     TIMESTAMP,
    CONSTRAINT PK_CXMT_TBL_ACCESS PRIMARY KEY (ACCESS_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;

-- 表权限
CREATE TABLE CXMT_TABLE_PERMISSIONS (
    PERMISSION_ID VARCHAR2(36) NOT NULL,
    ACCESS_ID     VARCHAR2(36) NOT NULL,
    USER_ID       VARCHAR2(36) NOT NULL,
    ALLOW_SELECT  NUMBER(1)    DEFAULT 0,
    ALLOW_INSERT  NUMBER(1)    DEFAULT 0,
    ALLOW_UPDATE  NUMBER(1)    DEFAULT 0,
    ALLOW_DELETE  NUMBER(1)    DEFAULT 0,
    GRANTED_BY    VARCHAR2(36),
    GRANTED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    STATUS        NUMBER(1)    DEFAULT 1,
    CONSTRAINT PK_CXMT_TBL_PERM PRIMARY KEY (PERMISSION_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;

-- DELETE 模板
CREATE TABLE CXMT_DELETE_TEMPLATES (
    TEMPLATE_ID       VARCHAR2(36)  NOT NULL,
    TEMPLATE_NAME     VARCHAR2(64)  NOT NULL,
    CONNECTION_ID     VARCHAR2(36)  NOT NULL,
    TABLE_NAME        VARCHAR2(128) NOT NULL,
    TEMPLATE_SQL      CLOB          NOT NULL,
    PARAMETERS_JSON   CLOB,
    MAX_AFFECTED_ROWS NUMBER(10)    DEFAULT 1000,
    STATUS            NUMBER(1)     DEFAULT 0,
    VERSION           NUMBER(4)     DEFAULT 1,
    CREATED_BY        VARCHAR2(36),
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    APPROVED_BY       VARCHAR2(36),
    APPROVED_AT       TIMESTAMP,
    FIRST_EXECUTED_AT TIMESTAMP,
    CONSTRAINT PK_CXMT_DEL_TEMPLATE PRIMARY KEY (TEMPLATE_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;

-- 白名单规则
CREATE TABLE CXMT_WHITELIST_RULES (
    RULE_ID         VARCHAR2(36)  NOT NULL,
    RULE_NAME       VARCHAR2(64)  NOT NULL,
    TABLE_NAME      VARCHAR2(128) NOT NULL,
    DATABASE_TYPE   NUMBER(1)     NOT NULL,
    ALLOWED_COLUMNS CLOB,
    MAX_AFFECTED    NUMBER(10)    DEFAULT 1000,
    TIME_WINDOW     VARCHAR2(64),
    STATUS          NUMBER(1)     DEFAULT 1,
    CREATED_BY      VARCHAR2(36),
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CXMT_WL_RULES PRIMARY KEY (RULE_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;

-- 审批流程实例
CREATE TABLE CXMT_APPROVAL_INSTANCES (
    INSTANCE_ID  VARCHAR2(36) NOT NULL,
    REQUEST_TYPE VARCHAR2(32) NOT NULL,
    REQUEST_ID   VARCHAR2(36) NOT NULL,
    STATUS       NUMBER(1)    DEFAULT 0,
    CURRENT_NODE NUMBER(2)    DEFAULT 0,
    NODES_JSON   CLOB         NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    CONSTRAINT PK_CXMT_APPROVAL PRIMARY KEY (INSTANCE_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;

-- 审批记录
CREATE TABLE CXMT_APPROVAL_RECORDS (
    RECORD_ID     VARCHAR2(36)  NOT NULL,
    INSTANCE_ID   VARCHAR2(36)  NOT NULL,
    NODE_ID       VARCHAR2(36)  NOT NULL,
    APPROVER_ID   VARCHAR2(36)  NOT NULL,
    APPROVER_ROLE NUMBER(1),
    ACTION        VARCHAR2(16)  NOT NULL,
    COMMENT_TEXT  VARCHAR2(512),
    SIGNATURE     VARCHAR2(256),
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CXMT_APPROVAL_REC PRIMARY KEY (RECORD_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;

-- 环境切换日志
CREATE TABLE CXMT_ENV_SWITCH_LOG (
    LOG_ID           VARCHAR2(36) NOT NULL,
    FROM_ENV         VARCHAR2(8)  NOT NULL,
    TO_ENV           VARCHAR2(8)  NOT NULL,
    SWITCHED_BY      VARCHAR2(36) NOT NULL,
    SWITCHED_BY_ROLE NUMBER(1)    NOT NULL,
    CLIENT_IP        VARCHAR2(32),
    REASON           VARCHAR2(256),
    CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CXMT_ENV_SWITCH PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_AUDIT;
CREATE INDEX IDX_ENV_SWITCH_TIME ON CXMT_ENV_SWITCH_LOG(CREATED_AT) TABLESPACE CXMT_IDX;

-- 会话环境覆盖
CREATE TABLE CXMT_SESSION_ENV_OVERRIDE (
    SESSION_ID   VARCHAR2(64) NOT NULL,
    USER_ID      VARCHAR2(36) NOT NULL,
    OVERRIDE_ENV VARCHAR2(8)  NOT NULL,
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXPIRES_AT   TIMESTAMP NOT NULL,
    CONSTRAINT PK_CXMT_SESSION_ENV PRIMARY KEY (SESSION_ID) USING INDEX TABLESPACE CXMT_IDX
) TABLESPACE CXMT_DATA;

-- 触发器：自动更新 UPDATED_AT
CREATE OR REPLACE TRIGGER TRG_USERS_UPDATED
BEFORE UPDATE ON CXMT_USERS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/
CREATE OR REPLACE TRIGGER TRG_DB_CONN_UPDATED
BEFORE UPDATE ON CXMT_DB_CONNECTIONS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- 默认 SysAdmin 账号（密码：admin@123）
-- 注意：PASSWORD_HASH/PASSWORD_SALT 此处为占位，首次启动 Web.Api 会写入真实哈希
INSERT INTO CXMT_USERS (USER_ID, USER_NAME, PASSWORD_HASH, PASSWORD_SALT, DISPLAY_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES ('SYSADMIN001', 'admin', 'PLACEHOLDER_HASH', 'PLACEHOLDER_SALT', '系统管理员', 3, 1, SYSTIMESTAMP);
COMMIT;
