<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CXMTCode.Plugins.Oracle19c</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CXMTCode.Plugins.Common\CXMTCode.Plugins.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.6.1" />
  </ItemGroup>
</Project>
