<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CXMTCode.Modules.Schema</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\01-Kernel\CXMTCode.Kernel.Contracts\CXMTCode.Kernel.Contracts.csproj" />
    <ProjectReference Include="..\..\01-Kernel\CXMTCode.Kernel\CXMTCode.Kernel.csproj" />
    <ProjectReference Include="..\..\02-Plugins\CXMTCode.Plugins.Common\CXMTCode.Plugins.Common.csproj" />
    <ProjectReference Include="..\..\05-Infrastructure\CXMTCode.Infrastructure\CXMTCode.Infrastructure.csproj" />
    <ProjectReference Include="..\..\05-Infrastructure\CXMTCode.Infrastructure.Db\CXMTCode.Infrastructure.Db.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.1" />
  </ItemGroup>
</Project>
